AWSTemplateFormatVersion: "2010-09-09"
Resources:

  ECSCluster:
    Type: AWS::ECS::Cluster

  ExecutionRole:
    Type: AWS::IAM::Role   #  it will create a IAM role based on policy
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:          # policy of iam role
        - PolicyName: AmazonECSTaskExecutionRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:GetAuthorizationToken
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  TaskDefinition:                            # task difination
    Type: AWS::ECS::TaskDefinition                
    Properties:
      Family: hello-nginx-task
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      ContainerDefinitions:
        - Name: hello-nginx
          Image: "nginxdemos/hello"
          PortMappings:
            - ContainerPort: 80

  ECSService:        # service defination
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      LaunchType: FARGATE
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - "subnet-0a6157d7d441d2d9d"  
            - "subnet-0f19bb3be4450ffed"
            - "subnet-065bc8e6375c9b10e"
          SecurityGroups: [!Ref ECSSecurityGroup]  

  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup       # security group for ecs
    Properties:
      GroupDescription: Allow traffic to ECS tasks
      VpcId: "vpc-09882a0ca28e27d09"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80  # default port
          ToPort: 80
          CidrIp: 0.0.0.0/0